### ISSUE TITLE
Проблемы с UI тестами. 

### ISSUE THREAD

**Issue by polyak01** [ArturVasilov/AndroidSchool#1]
Добрый день) Спасибо за прекрасный Android курс.

Нашёл небольшую проблему. UI тесты некорректно воспроизводятся. Глохнет всё на testSuccessAuth. Стягивал ваш репозиторий дабы запустить UI тесты. Возможно сделал что-то не правильно либо же стоит добавить свой токен?

**Comment by ArturVasilov** [comment]
Проблемы исправлены. Было две причины: 

1. RxJava converter для ретрофита тянет за собой rxjava 1.3.0, в которой выпилены некоторые методы, из-за чего все падает. Эта проблема актуальна почти для всех проектов, они будут исправлены позже #2
2. Почему-то Espresso перестал ждать закрытия диалогов сам по себе, пришлось добавлять IdlingResource. 

Спасибо за найденную проблему.
